export const reciptData = [
  {
    description: "Medicine A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Optic (Glass)",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Grant A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Staff Security",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Health Card Sale A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Registration Fee",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Profit of Optic (Glass)",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Profit of Medicine Sale",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Test-Investigation A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Service Charge of Singer",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Stock of Goods-Singer",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Telemedicine Fee",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Advise Fee A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Profit-Diabetes Test",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Ray Therapy",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Advance A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Blood Groupping",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Stock of Goods-Walton",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Service Charge of Walton",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
];
export const paymentData = [
  {
    description: "Advance A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Diabetes Test Steeps",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Grant A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Staff Security",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Salary & Allowance A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Travelling & Conveyance A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Office Maintenance A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Entertainment A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Mobile & Telephone Bill A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Camp Arrangement Fee",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Stock of Goods-Singer",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Commission of Singer",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Optic (Glass)",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Commission of Walton",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Stock of Goods-Walton",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Bank Charge & Commission A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Service Charge paid Head Office",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
  {
    description: "Printing & Stationary A/C",
    thisMonthTo: 0,
    thisYearTo: 0,
    cumulativeUpTo: 0,
  },
];
