export const PaymentTableData = [
  {
    label: "Liberties",
    items: [
      { label: "Office Equipment A/C", name: "Office_Equipment_A_C" },
      { label: "Health Equipment", name: "Health_Equipment" },
      { label: "Furniture & Fixture A/C", name: "Furniture_Fixture_A_C" },
      { label: "Vehicle A/C", name: "Vehicle_A_C" },
      { label: "Service Charge paid to Ho", name: "Service_Charge_paid_to_Ho" },
      { label: "Advance A/C", name: "Advance_A_C" },
      { label: "Medicine A/C", name: "Medicine_A_C" },
      { label: "Optic (Glass)", name: "Optic_Glass" },
      { label: "Diabetes Steep", name: "Diabetes_Steep" },
      { label: "Grant A/C", name: "Grant_A_C" },
      { label: "Staff Scecurity", name: "Staff_Scecurity" },
      { label: "FDR A/C", name: "FDR_A_C" },
    ],
  },
  {
    label: "Health Card Sale",
    items: [{ label: "Dhanmondi", name: "Dhanmondi" }],
  },

  {
    label: "Other Expenses",
    items: [
      {
        label: "Bank Charge & Commission A/C",
        name: "Bank_Charge_Commission_A_C",
      },
      { label: "Salary & Allowance A/C", name: "Salary_Allowance_A_C" },
      {
        label: "Travelling & Conveyance A/C",
        name: "Travelling_Conveyance_A_C",
      },
      { label: "Printing & Stationary A/C", name: "Printing_Stationary_A_C" },
      { label: "Office Maintenance A/C", name: "Office_Maintenance_A_C" },
      { label: "Entertainment A/C", name: "Entertainment_A_C" },
      { label: "Fuel & Lubricant A/C", name: "Fuel_Lubricant_A_C" },
      { label: "Misc. Expenses A/C", name: "Misc_Expenses_A_C" },
      { label: "Postage & Telegram A/C", name: "Postage_Telegram_A_C" },
      {
        label: "Mobile & Telephone Bill A/C",
        name: "Mobile_Telephone_Bill_A_C",
      },
      { label: "Training & Workshop A/C", name: "Training_Workshop_A_C" },
      { label: "Doctors Fee A/C", name: "Doctors_Fee_A_C" },
      { label: "Pregnancy Test Steep", name: "Pregnancy_Test_Steep" },
      { label: "Commision Expenses A/C", name: "Commision_Expenses_A_C" },
      { label: "Nebulization", name: "Nebulization" },
      { label: "Camp arrangement", name: "Camp_arrangement" },
      { label: "Office Rent", name: "Office_Rent" },
    ],
  },

  // { label: "", name: "" }, // Empty row
  {
    label: "EYE PROGRAM",
    items: [
      { label: "Registration Fee", name: "Registration_Fee" },
      { label: "Profit of Optic (Glass) 140Tk", name: "Profit_of_Optic_Glass" },
      {
        label: "Profit of Medicine sale 20%",
        name: "Profit_of_Medicine_sale_20",
      },
      { label: "Eye Test (Investigation)", name: "Eye_Test_Investigation" },
    ],
  },

  {
    label: "Consumer Program",
    items: [
      { label: "Stock of Goods Singer", name: "Stock_of_Goods_Singer" },
      { label: "Commision of Singer", name: "Commision_of_Singer" },
      { label: "Singer service charge H/O", name: "Singer_service_charge_HO" },
      { label: "Stock of Goods Walton", name: "Stock_of_Goods_Walton" },
      { label: "Commision of Walton", name: "Commision_of_Walton" },
      { label: "Walton service charge H/O", name: "Walton_service_charge_HO" },
    ],
  },

  {
    label: "Closing Blance",
    items: [
      { label: "Cash in hand", name: "Cash_in_Hand" },
      { label: "Cash at Bank", name: "Cash_at_Bank" },
    ],
  },
];
export const ReceiptTableData = [
  {
    label: "Opening Blance",
    items: [
      { label: "Cash in hand", name: "Cash_in_Hand" },
      { label: "Cash at Bank", name: "Cash_at_Bank" },
      { label: "Advance A/C", name: "Advance_A_C" },
      { label: "Medicine A/c 80%", name: "Medicine_A_C" },
      { label: "Optic (Glass) 60Tk", name: "Optic_(Glass)" },
      { label: "Diabetes Steep- (7.43Tk)", name: "Diabetes_Steep-743Tk" },
      { label: "Grant A/C", name: "Grant_A_C" },
      { label: "SWF", name: "SWF" },
      { label: "Staff Scecurity", name: "Staff_Scecurity" },
      { label: "FDR A/C", name: "FDR_A_C" },
      { label: "FDR Interast A/C", name: "FDR_Interast_A_C" },
    ],
  },
  {
    label: "Health Card Sale",
    items: [{ label: "Health Card Sale A/C", name: "Health_Card_Sale_A_C" }],
  },
  {
    label: "EYE PROGRAM",
    items: [
      { label: "Registration Fee", name: "Registration_Fee" },
      { label: "Profit of Optic (Glass) 140Tk", name: "Profit_of_Optic_Glass" },
      { label: "Profit of Medicine sale 20%", name: "Profit_of_Medicine_sale" },
      { label: "Eye Test (Investigation)", name: "Eye_Test_Investigation" },
    ],
  },
  {
    label: "Consumer Program",
    items: [
      {
        label: "Stock of Goods Singer (Purchase value)",
        name: "Stock_of_Goods_Singer_Purchase_value",
      },
      { label: "Service Charge of Singer", name: "Service_Charge_of_Singer" },
      {
        label: "Stock of Goods Walton (Purchase value)",
        name: "Stock_of_Goods_Walton_Purchase_value",
      },
      { label: "Service Charge of Walton", name: "Service_Charge_of_Walton" },
    ],
  },
  {
    label: "Others",
    items: [
      { label: "Bank Interest A/C", name: "Bank_Interest_A_C" },
      { label: "Telemedicine Fee A/C", name: "Telemedicine_Fee_A_C" },
      { label: "Advise Fee A/C", name: "Advise_Fee_A_C" },
      { label: "Misc. Income A/C", name: "Misc_Income_A_C" },
      {
        label: "Profit of Diabetes test (17.57TK)",
        name: "Profit_of_Diabetes_test_1757TK",
      },
      { label: "Pregnancy Test", name: "Pregnancy_Test" },
      { label: "Nebulization", name: "Nebulization" },
      { label: "Patient Visit Fee", name: "Patient_Visit_Fee" },
      { label: "Ray Therapy", name: "Ray_Therapy" },
      { label: "Traning Fee income", name: "Traning_Fee_income" },
      { label: "Dressing Fee", name: "Dressing_Fee" },
      { label: "Blood Grupping", name: "Blood_Grupping" },
      { label: "Doctors Fee", name: "Doctors_Fee" },
    ],
  },
];
export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const receiptVariables = [
  "Cash_in_Hand",
  "Cash_at_Bank",
  "Advance_A_C",
  "Medicine_A_C",
  "Optic_Glass",
  "Diabetes_Steep_743Tk",
  "Grant_A_C",
  "SWF",
  "Staff_Scecurity",
  "FDR_A_C",
  "FDR_Interast_A_C",
  "Health_Card_Sale_A_C",
  "Registration_Fee",
  "Profit_of_Optic_Glass",
  "Profit_of_Medicine_sale",
  "Eye_Test_Investigation",
  "Stock_of_Goods_Singer_Purchase_value",
  "Service_Charge_of_Singer",
  "Stock_of_Goods_Walton_Purchase_value",
  "Service_Charge_of_Walton",
  "Bank_Interest_A_C",
  "Telemedicine_Fee_A_C",
  "Advise_Fee_A_C",
  "Misc_Income_A_C",
  "Profit_of_Diabetes_test_1757TK",
  "Pregnancy_Test",
  "Nebulization",
  "Patient_Visit_Fee",
  "Ray_Therapy",
  "Traning_Fee_income",
  "Dressing_Fee",
  "Blood_Grupping",
  "Doctors_Fee",
];
export const paymentVariables = [
  "Office_Equipment_A_C",
  "Health_Equipment",
  "Furniture_Fixture_A_C",
  "Vehicle_A_C",
  "Service_Charge_paid_to_Ho",
  "Advance_A_C",
  "Medicine_A_C",
  "Optic_Glass",
  "Diabetes_Steep",
  "Grant_A_C",
  "Staff_Scecurity",
  "FDR_A_C",
  "Dhanmondi",
  "Bank_Charge_Commission_A_C",
  "Salary_Allowance_A_C",
  "Travelling_Conveyance_A_C",
  "Printing_Stationary_A_C",
  "Office_Maintenance_A_C",
  "Entertainment_A_C",
  "Fuel_Lubricant_A_C",
  "Misc_Expenses_A_C",
  "Postage_Telegram_A_C",
  "Mobile_Telephone_Bill_A_C",
  "Training_Workshop_A_C",
  "Doctors_Fee_A_C",
  "Pregnancy_Test_Steep",
  "Commision_Expenses_A_C",
  "Nebulization",
  "Camp_arrangement",
  "Office_Rent",
  "Registration_Fee",
  "Profit_of_Optic_Glass",
  "Profit_of_Medicine_sale_20",
  "Eye_Test_Investigation",
  "Stock_of_Goods_Singer",
  "Commision_of_Singer",
  "Singer_service_charge_HO",
  "Stock_of_Goods_Walton",
  "Commision_of_Walton",
  "Walton_service_charge_HO",
  "Cash_in_Hand",
  "Cash_at_Bank",
];

export function NamesArray(TableData) {
  const namesArray = TableData.flatMap((category) =>
    category.items.map((item) => item.name)
  );
  return namesArray;
}
export const ReceiptTableVariables = [
  { label: "Office Equipment A/C", name: "Office_Equipment_A_C" },
  { label: "Health Equipment", name: "Health_Equipment" },
  { label: "Furniture & Fixture A/C", name: "Furniture_Fixture_A_C" },
  { label: "Vehicle A/C", name: "Vehicle_A_C" },
  { label: "Service Charge paid to Ho", name: "Service_Charge_paid_to_Ho" },
  { label: "Advance A/C", name: "Advance_A_C" },
  { label: "Medicine A/C", name: "Medicine_A_C" },
  { label: "Optic (Glass)", name: "Optic_Glass" },
  { label: "Diabetes Steep", name: "Diabetes_Steep" },
  { label: "Grant A/C", name: "Grant_A_C" },
  { label: "Staff Scecurity", name: "Staff_Scecurity" },
  { label: "FDR A/C", name: "FDR_A_C" },
  { label: "Dhanmondi", name: "Dhanmondi" },
  {
    label: "Bank Charge & Commission A/C",
    name: "Bank_Charge_Commission_A_C",
  },
  { label: "Salary & Allowance A/C", name: "Salary_Allowance_A_C" },
  {
    label: "Travelling & Conveyance A/C",
    name: "Travelling_Conveyance_A_C",
  },
  { label: "Printing & Stationary A/C", name: "Printing_Stationary_A_C" },
  { label: "Office Maintenance A/C", name: "Office_Maintenance_A_C" },
  { label: "Entertainment A/C", name: "Entertainment_A_C" },
  { label: "Fuel & Lubricant A/C", name: "Fuel_Lubricant_A_C" },
  { label: "Misc. Expenses A/C", name: "Misc_Expenses_A_C" },
  { label: "Postage & Telegram A/C", name: "Postage_Telegram_A_C" },
  {
    label: "Mobile & Telephone Bill A/C",
    name: "Mobile_Telephone_Bill_A_C",
  },
  { label: "Training & Workshop A/C", name: "Training_Workshop_A_C" },
  { label: "Doctors Fee A/C", name: "Doctors_Fee_A_C" },
  { label: "Pregnancy Test Steep", name: "Pregnancy_Test_Steep" },
  { label: "Commision Expenses A/C", name: "Commision_Expenses_A_C" },
  { label: "Nebulization", name: "Nebulization" },
  { label: "Camp arrangement", name: "Camp_arrangement" },
  { label: "Office Rent", name: "Office_Rent" },
  { label: "Registration Fee", name: "Registration_Fee" },
  { label: "Profit of Optic (Glass) 140Tk", name: "Profit_of_Optic_Glass" },
  {
    label: "Profit of Medicine sale 20%",
    name: "Profit_of_Medicine_sale",
  },
  {
    label: "Profit of Medicine sale 20%",
    name: "Profit_of_Medicine_sale_20",
  },
  { label: "Eye Test (Investigation)", name: "Eye_Test_Investigation" },
  { label: "Stock of Goods Singer", name: "Stock_of_Goods_Singer" },
  {
    label: "Stock of Goods Singer (Purchase value)",
    name: "Stock_of_Goods_Singer_Purchase_value",
  },
  { label: "Commision of Singer", name: "Commision_of_Singer" },
  { label: "Singer service charge H/O", name: "Singer_service_charge_HO" },
  { label: "Stock of Goods Walton", name: "Stock_of_Goods_Walton" },
  { label: "Service Charge of Singer", name: "Service_Charge_of_Singer" },
  { label: "Service Charge of Walton", name: "Service_Charge_of_Walton" },
  {
    label: "Stock of Goods Walton (Purchase value)",
    name: "Stock_of_Goods_Walton_Purchase_value",
  },
  { label: "Commision of Walton", name: "Commision_of_Walton" },
  { label: "Walton service charge H/O", name: "Walton_service_charge_HO" },
  { label: "Cash in hand", name: "Cash_in_Hand" },
  { label: "Cash at Bank", name: "Cash_at_Bank" },
  { label: "SWF", name: "SWF" },
  { label: "FDR Interast A/C", name: "FDR_Interast_A_C" },
  { label: "Health Card Sale A/C", name: "Health_Card_Sale_A_C" },
  { label: "Bank Interest A/C", name: "Bank_Interest_A_C" },
  { label: "Telemedicine Fee A/C", name: "Telemedicine_Fee_A_C" },
  { label: "Advise Fee A/C", name: "Advise_Fee_A_C" },
  { label: "Misc. Income A/C", name: "Misc_Income_A_C" },
  {
    label: "Profit of Diabetes test (17.57TK)",
    name: "Profit_of_Diabetes_test_1757TK",
  },
  { label: "Pregnancy Test", name: "Pregnancy_Test" },
  { label: "Patient Visit Fee", name: "Patient_Visit_Fee" },
  { label: "Ray Therapy", name: "Ray_Therapy" },
  { label: "Traning Fee income", name: "Traning_Fee_income" },
  { label: "Dressing Fee", name: "Dressing_Fee" },
  { label: "Blood Grupping", name: "Blood_Grupping" },
  { label: "Doctors Fee", name: "Doctors_Fee" },
];

export function getLabelName(name) {
  const variable = ReceiptTableVariables.find(
    (variable) => variable.name === name
  );

  return variable ? variable.label : name;
}
